version: 1
formatters:
    simple:
        format: '%(asctime)s %(name)-12s %(levelname)-8s %(message)s'
    complex:
        format: '%(asctime)s [%(levelname)s] |%(threadName)s (%(thread)d)| %(name)s.%(funcName)s {%(filename)s #%(lineno)d}: %(message)s'
handlers:
    screen:
        class: logging.StreamHandler
        formatter: simple
        level: DEBUG
    error_file:
        class: logging.handlers.TimedRotatingFileHandler
        filename: logs/roa_api_errors.log
        when: midnight
        backupCount: 7
        formatter: complex
        level: WARNING
root:
    handlers: [screen, error_file]
    level: DEBUG
